---
public_protocol: https
private_protocol: http
domain_name: "{{ subdomain }}.{{ hosted_zone }}"
content_public_url: "{{ public_protocol }}://{{ domain_name }}"
authdb_server_url: "{{ private_protocol }}://127.0.0.1:8000"
customs_server_url: "{{ private_protocol }}://127.0.0.1:7000"
auth_mailer_url: "{{ private_protocol }}://127.0.0.1:10136"
auth_sns_arn: ""
auth_public_url: "{{ public_protocol }}://{{ domain_name }}/auth"
auth_private_port: 9000
auth_git_repo: https://github.com/mozilla/fxa-auth-server.git
auth_git_version: master
auth_mail_host: 127.0.0.1
auth_mail_port: 25
auth_mail_sender: "Firefox Accounts <verification@{{ domain_name }}>"
trusted_jku_123done: "{{ public_protocol }}://123done-{{ domain_name }}/.well-known/public-keys"
trusted_jku_321done: "{{ public_protocol }}://321done-{{ domain_name }}/.well-known/public-keys"
oauth_domain_name: "oauth-{{ domain_name }}"
oauth_public_url: "{{ public_protocol }}://{{ oauth_domain_name }}"
