---

- name: Configure instance
  hosts: localhost
  connection: local
  vars_files:
    - "environments/{{ stack_name }}.yml"
  vars:
    authdb_primary_host: "{{ rds_host }}"
    authdb_primary_password: "{{ rds_password }}"
    authdb_replica_host: "{{ rds_host }}"
    authdb_replica_password: "{{ rds_password }}"
    oauth_db_host: "{{ rds_host }}"
    oauth_db_password: "{{ rds_password }}"
    profile_db_host: "{{ rds_host }}"
    profile_db_password: "{{ rds_password }}"
    sync_db_host: "{{ rds_host }}"
    sync_db_password: "{{ rds_password }}"
  roles:
    - ses
    - memcached
    - datadog
    - auth
    - authdb
    - content
    - basket-proxy
    - oauth
    - oauth-console
    - profile
    - sync
    - rp
    - rp-untrusted
    - able
    - log
    - cron_update
    - team
