---
public_protocol: https
private_protocol: http
domain_name: "{{ subdomain }}.{{ hosted_zone }}"
profile_private_port: 9011
profile_private_static_port: 9012
profile_git_repo: https://github.com/mozilla/fxa-profile-server.git
profile_git_version: master
redis_docker_tag: 3.2-alpine
redis_docker_state: started
profile_public_url: "{{ public_protocol }}://{{ domain_name }}/profile"
profile_db_host: 127.0.0.1
profile_db_password:
oauth_domain_name: "oauth-{{ domain_name }}"
oauth_public_url: "{{ public_protocol }}://{{ oauth_domain_name }}"
