---

- name: configure nginx upstream
  sudo: true
  template: src=upstream.conf.j2 dest=/etc/nginx/conf.d/upstream/http_syncserver.conf
  notify: reload nginx config

- name: configure nginx location
  sudo: true
  template: src=nginx.conf.j2 dest=/etc/nginx/conf.d/location/http_syncserver.conf
  notify: reload nginx config

- name: install python build environment
  sudo: true
  yum: name=python-devel state=present

- name: install mysql command-line tools
  sudo: true
  yum: name=mysql

- name: install syncserver build dependencies
  sudo: true
  pip: name=virtualenv state=present

#
# "legacy" boxes (e.g., 'latest', 'stable', other) have installed `virtualenv`
# in `/usr/bin` Newer boxes put `virtualenv` in `/usr/local/bin`, but other code
# wants to find `virtualenv` in `/usr/bin`. So attempt to symlink but ignore
# failures.
#
- name: symlink virtualenv
  sudo: true
  failed_when: false
  changed_when: false
  file: src=/usr/local/bin/virtualenv dest=/usr/bin/virtualenv state=link

- name: create syncserver database
  sudo: true
  command: mysql --host={{ sync_db_host }} --user=root --password={{ sync_db_password }} -e "CREATE DATABASE IF NOT EXISTS sync"
  changed_when: false

- name: install syncserver
  tags: code
  sudo: true
  sudo_user: app
  git: repo={{ sync_git_repo }}
       dest=/data/syncserver
       version={{ sync_git_version }}
       force=true
  notify:
    - build syncserver virtualenv
    - restart syncserver process

- name: temp reload
  command: "true"
  notify:
    - build syncserver virtualenv
    - restart syncserver process

- name: supervise syncserver
  sudo: true
  copy: src=syncserver.conf dest=/etc/supervisor.d/syncserver.conf
  notify: update supervisor

- name: configure syncserver
  sudo: true
  sudo_user: app
  template: src=syncserver.ini.j2 dest=/data/syncserver/syncserver.dev.ini
  notify: restart syncserver process

- name: install synclogtailer
  sudo: true
  sudo_user: app
  git: repo=https://github.com/dannycoates/synclogtailer.git
       dest=/data/synclogtailer
       force=true
  notify:
    - install synclogtailer dependencies
    - restart synclogtailer

- name: supervise synclogtailer
  sudo: true
  copy: src=synclogtailer.conf dest=/etc/supervisor.d/synclogtailer.conf
  notify: update supervisor

- name: install syncmetrics
  sudo: true
  sudo_user: app
  git: repo=https://github.com/dannycoates/syncmetrics.git
       dest=/data/syncmetrics
       force=true
  notify:
    - install syncmetrics dependencies
    - restart syncmetrics

- name: configure syncmetrics
  sudo: true
  sudo_user: app
  template: src=syncmetrics.json.j2 dest=/data/syncmetrics/config.json
  notify: restart syncmetrics

- name: supervise syncmetrics
  sudo: true
  copy: src=syncmetrics.conf dest=/etc/supervisor.d/syncmetrics.conf
  notify: update supervisor

- name: install psql client tools
  sudo: true
  yum: name=postgresql94 state=present

- meta: flush_handlers
